spring:
  rabbitmq:
    host: 192.168.59.130
    username: woldier
    password: woldier
    virtual-host: /woldier
    port: 5672
    publisherConfirms: true #publisherConfirms增强
    publisherReturns: true #publisherConfirms增强